[build]
  publish = "_site"
  command = "npm run build"

# Redirects and headers
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404

[dev]
  command = "npm run dev"
  port = 8080
  publish = "_site"

# Enable Netlify CMS proxy server for local development
[[plugins]]
  package = "@netlify/plugin-local-install-core"